# Archivo de configuraci칩n para Rasa NLU y Core

# Configuraci칩n del procesador de lenguaje natural (NLU)
language: es
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
#  - name: CRFEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 600
  - name: EntitySynonymMapper

# Configuraci칩n del modelo de di치logo (Core)
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 600
  - name: RulePolicy
