# config.yml

language: "es"

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
  - name: FormPolicy
